# Generated by Django 5.2.3 on 2025-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product_image_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_collection',
            field=models.BooleanField(default=False, verbose_name='Новая коллекция'),
        ),
    ]
